name: prepare module
on: push

run: ./RPi4-Modem5g/rpi_5g.sh.sh
runs-on: ubuntu-latest
shell: bash
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./RPi4-Modem5g/rpi_5g.sh.sh
         ./RPi4-Modem5g/rpi_5g.sh.sh
      shell: bash

