name: Bash CI/CD Pipeline

on:
  push:
    branches:
      - main  # zmień to na nazwę głównej gałęzi w twoim repozytorium

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: ShellCheck
      uses: koalaman/shellcheck-action@v1
      with:
        shellcheck-version: 'latest'


    - name: Run tests
      run: bash rpi_5g.sh  # Zastąp test.sh odpowiednim skryptem testowym
